### PR TITLE
Fixed 🪝🏗

### PR DESCRIPTION
**Pull request by Vest**
Fixed Day 2.

### CODE REVIEW

**Comment by Vest** [comment]
@shartf please review.

**Review by Padavan — APPROVED** [review]
LGTM

**Comment by shartf** [comment]
@Vest Is it safe rust? You are making an .unwrap, it can panic. Errors should be handled!

**Comment by Vest** [comment]
@shartf, this is the explicit unwrap. The application will not fail, I have checked. The answer is close to 400.

**Comment by shartf** [comment]
@Vest I have tried ~400 in AoC. Unfortunately, it fails.

**Pull request merged**
